colorscheme vividchalk
syntax on
" presentation settings
set number              " precede each line with its line number
set numberwidth=3       " number of culumns for line numbers
set textwidth=0         " Do not wrap words (insert)
set wrapmargin=0        " Do not wrap words (insert)
set nowrap              " Do not wrap words (view)
set showcmd             " Show (partial) command in status line.
set showmatch           " Show matching brackets.
set ruler               " line and column number of the cursor position
set wildmenu            " enhanced command completion
set visualbell          " use visual bell instead of beeping
set laststatus=2        " always show the status line
" set listchars=tab:▷⋅,trail:·,eol:$
set listchars=tab:▷⋅,trail:·
set list
" highlight spell errors
hi SpellErrors guibg=red guifg=black ctermbg=red ctermfg=black

" behavior
" ignore these files when completing names and in explorer
set wildignore=.svn,CVS,.git,.hg,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.xpm,*.gif
set shell=/bin/bash     "use bash for shell commands
set autowriteall        "Automatically save before commands like :next and :make
set hidden              "enable multiple modified buffers
set history=1000
set autoread            "automatically read file that has been changed on disk and doesn't have changes in vim
set backspace=indent,eol,start
set guioptions-=T       "disable toolbar"
set completeopt=menuone,preview
let bash_is_sh=1        "syntax shell files as bash scripts
set cinoptions=:0,(s,u0,U1,g0,t0 " some indentation options ':h cinoptions' for details
set modelines=5         "number of lines to check for vim: directives at the start/end of file
"set fixdel		" fix terminal code for delete (if delete is broken but backspace works)
set autoindent          "automatically indent new line

" Whitespace stuff
set wm=2		"number of spaces in a word margin
set ts=2                "number of spaces in a tab
set sw=2                "number of spaces for indent
set sts=2		"number of spaces while performing editing operations
set et                  "expand tabs into spaces

set ttimeoutlen=50      "fast Esc to normal mode

" mouse settings
"if has("mouse")
  "set mouse=a
"endif
set mouse=niv "or set mouse=a
set clipboard=unnamed
set mousehide           " Hide mouse pointer on insert mode."
"set mousefocus
